
name: Build C++ EXE

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4

      - name: Setup C++ Compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile C++ to EXE
        run: cl /EHsc main.cpp /Fe:main.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: hasil-exe
          path: main.exe
